Yua's share
SUSTech-Application/SUSTechapplication pull request #115
Opened 2024-07-09 08:36 UTC by wma17

2024-08-15 04:25 UTC, sghuang19 requested changes
这些地方需要调整，如果不知道具体怎么修改/提交欢迎提问

2024-08-15 04:25 UTC, sghuang19 commented on docs/grad-application/math/statistics/yua/me
这个空文件需要删除一下

2024-08-15 04:25 UTC, sghuang19 commented on docs/grad-application/math/statistics/[US]-20-Yua.md
> +![snacks](/yua/snacks.png)
这个链接 broken 了，应该用相对路径

```suggestion
![snacks](./yua/snacks.png)
```

2024-08-15 04:25 UTC, sghuang19 commented on docs/grad-application/math/statistics/[US]-20-Yua.md
> +16级数学系徐源诚学长：[PhD申请的“游戏规则”、科研、英语、绩点与其他](https://sustech-application.com/?utm_source=online#/grad-application/math/applied-mathematics/[US]-16-xuyuancheng)
去掉没用的 param

```suggestion
16级数学系徐源诚学长：[PhD申请的“游戏规则”、科研、英语、绩点与其他](https://sustech-application.com/#/grad-application/math/applied-mathematics/[US]-16-xuyuancheng)
```

2024-08-15 04:25 UTC, sghuang19 commented on docs/grad-application/math/statistics/[US]-20-Yua.md
> +> 6. OIST：Okinawa Institute of Sicence and Technology 只颁发5年博士学位、纯英环境（日本人占比仅30%）、在美丽的冲绳、宣传片：【OIST - University of the Future 新時代の教育研究を切り拓く】 https://www.bilibili.com/video/BV1yW411a7TG/?share_source=co
同样去一下 query string，同时注意链接格式

```suggestion
> 6. OIST：Okinawa Institute of Sicence and Technology 只颁发5年博士学位、纯英环境（日本人占比仅30%）、在美丽的冲绳、宣传片：[【OIST - University of the Future 新時代の教育研究を切り拓く】](https://www.bilibili.com/video/BV1yW411a7TG/)
```

2024-08-15 04:25 UTC, sghuang19 commented on docs/grad-application/math/statistics/yua/snacks.png
考虑改用赞赏码而不是收款码？我觉得用赞赏码比较有格调哈哈哈😄

2024-08-15 04:27 UTC, sghuang19 commented
@Yujing27 还有没有别的问题？没有的话等修改提交就可以合并了，注意用 squash merge！ :heart: :heart:

2024-08-20 12:40 UTC, merged

2024-08-20 14:49 UTC, Yujing27 commented
@sghuang19 提到的问题已修改并合并，感谢投稿！